### ISSUE TITLE
Error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by Kmanjor** [dfguan/pin_hic#3]
Hi, 

I meet an error when installing pin_hic. The error has happened in 'build_graph' that is 'build_graph.c:62:2: error: ‘for’ loop initial declarations are only allowed in C99 mode'. Maybe I guess my gcc version is not right.
My gcc version is 4.8.5.
Could you help me?
Thanks~

Bests,
Kmanjor

Here are logs:

gcc -O2 -Wall -D VERBOSE -D PRINT_COVERAGE    -c -o bamlite.o bamlite.c
gcc -O2 -Wall -D VERBOSE -D PRINT_COVERAGE    -c -o bed.o bed.c
In file included from bed.c:23:0:
bed.c: In function ‘ks_seek’:
kseq.h:41:17: warning: no return statement in function returning non-void [-Wreturn-type]
  typedef struct __kstream_t { \
                 ^
kseq.h:160:2: note: in expansion of macro ‘__KS_TYPE’
  __KS_TYPE(type_t) \
  ^
kseq.h:167:57: note: in expansion of macro ‘KSTREAM_INIT2’
 #define KSTREAM_INIT(type_t, __read, __seek, __bufsize) KSTREAM_INIT2(static, type_t, __read, __seek,  __bufsize)
                                                         ^
bed.c:24:1: note: in expansion of macro ‘KSTREAM_INIT’
 KSTREAM_INIT(gzFile, gzread, gzseek, 0x10000)
 ^
gcc -O2 -Wall -D VERBOSE -D PRINT_COVERAGE    -c -o cdict.o cdict.c
cdict.c: In function ‘cd_filt’:
cdict.c:83:3: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘size_t’ [-Wformat=]
   fprintf(stderr, "%d\t%d\t%d\n", t->lim, max_wt, sum_wt);
   ^
cdict.c: In function ‘cd2_set_lim’:
cdict.c:92:14: warning: unused variable ‘j’ [-Wunused-variable]
  uint32_t i, j;
              ^
gcc -O2 -Wall -D VERBOSE -D PRINT_COVERAGE    -c -o graph.o graph.c
In file included from graph.c:25:0:
graph.c: In function ‘ks_seek’:
kseq.h:41:17: warning: no return statement in function returning non-void [-Wreturn-type]
  typedef struct __kstream_t { \
                 ^
kseq.h:160:2: note: in expansion of macro ‘__KS_TYPE’
  __KS_TYPE(type_t) \
  ^
kseq.h:252:2: note: in expansion of macro ‘KSTREAM_INIT2’
  KSTREAM_INIT2(SCOPE, type_t, __read, __seek, 16384) \
  ^
kseq.h:257:43: note: in expansion of macro ‘KSEQ_INIT2’
 #define KSEQ_INIT(type_t, __read, __seek) KSEQ_INIT2(static, type_t, __read, __seek)
                                           ^
graph.c:33:1: note: in expansion of macro ‘KSEQ_INIT’
 KSEQ_INIT(gzFile, gzread, gzseek) 
 ^
graph.c: In function ‘simp_graph’:
graph.c:370:12: warning: unused variable ‘vt’ [-Wunused-variable]
  vertex_t *vt = g->vtx.vertices;
            ^
graph.c: In function ‘add_a’:
graph.c:874:6: warning: variable ‘node_n’ set but not used [-Wunused-but-set-variable]
  int node_n; 
      ^
graph.c: In function ‘cp_seq’:
graph.c:948:3: warning: array subscript has type ‘char’ [-Wchar-subscripts]
   for ( i = 0; i < len; ++i) s[i] = rc_table[t[len -i - 1]]; 
   ^
graph.c: In function ‘add_e’:
graph.c:817:11: warning: ‘wt’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  add_dedge(g, n1, d1 == '+', n2, d2 == '+', wt);
           ^
graph.c:817:11: warning: ‘d2’ may be used uninitialized in this function [-Wmaybe-uninitialized]
graph.c:817:11: warning: ‘d1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
graph.c:817:11: warning: ‘n2’ may be used uninitialized in this function [-Wmaybe-uninitialized]
graph.c: In function ‘add_p’:
graph.c:860:20: warning: ‘plen’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  if (ns.n) add_path(g, name, plen, ns.a, ns.n, name[0]=='c');
                    ^
graph.c:828:8: warning: ‘nodes_str’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  char *nodes_str;
        ^
graph.c: In function ‘add_a’:
graph.c:873:8: warning: ‘nodes_str’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  char *nodes_str;
        ^
gcc -O2 -Wall -D VERBOSE -D PRINT_COVERAGE    -c -o pin_10x.o pin_10x.c
gcc -O2 -Wall -D VERBOSE -D PRINT_COVERAGE    -c -o sdict.o sdict.c
gcc -O2 -Wall -D VERBOSE -D PRINT_COVERAGE    -c -o build_graph.o build_graph.c
build_graph.c: In function ‘col_ctgs_from_graph’:
build_graph.c:62:16: error: redeclaration of ‘i’ with no linkage
  for (uint32_t i = 0; i < ctgs->n_seq; ++i) fprintf(stderr, "ctgs: %s %d\n", ctgs->seq[i].name, ctgs->seq[i].is_circ);
                ^
build_graph.c:53:11: note: previous declaration of ‘i’ was here
  uint32_t i, j;
           ^
build_graph.c:62:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (uint32_t i = 0; i < ctgs->n_seq; ++i) fprintf(stderr, "ctgs: %s %d\n", ctgs->seq[i].name, ctgs->seq[i].is_circ);
  ^
build_graph.c:62:2: note: use option -std=c99 or -std=gnu99 to compile your code
build_graph.c:53:14: warning: unused variable ‘j’ [-Wunused-variable]
  uint32_t i, j;
              ^
build_graph.c: In function ‘print_cdict2’:
build_graph.c:143:12: warning: variable ‘icnt’ set but not used [-Wunused-but-set-variable]
   uint32_t icnt;
            ^
build_graph.c: In function ‘norm_links’:
build_graph.c:247:9: warning: variable ‘icnt’ set but not used [-Wunused-but-set-variable]
   float icnt;
         ^
build_graph.c: In function ‘nns_mst’:
build_graph.c:410:13: warning: unused variable ‘len2’ [-Wunused-variable]
    uint32_t len2 = ctgs->seq[ind].len;
             ^
build_graph.c:409:19: warning: unused variable ‘is_l2’ [-Wunused-variable]
    uint32_t is_l, is_l2;
                   ^
build_graph.c:409:13: warning: unused variable ‘is_l’ [-Wunused-variable]
    uint32_t is_l, is_l2;
             ^
build_graph.c:400:7: warning: unused variable ‘isf’ [-Wunused-variable]
   int isf = 1;
       ^
build_graph.c:398:12: warning: unused variable ‘len1’ [-Wunused-variable]
   uint32_t len1 = ctgs->seq[i].len;
            ^
build_graph.c:521:23: warning: unused variable ‘tt’ [-Wunused-variable]
     float hh, ht, th, tt, ort_cnt[4];
                       ^
build_graph.c:521:19: warning: unused variable ‘th’ [-Wunused-variable]
     float hh, ht, th, tt, ort_cnt[4];
                   ^
build_graph.c:521:15: warning: unused variable ‘ht’ [-Wunused-variable]
     float hh, ht, th, tt, ort_cnt[4];
               ^
build_graph.c:521:11: warning: unused variable ‘hh’ [-Wunused-variable]
     float hh, ht, th, tt, ort_cnt[4];
           ^
build_graph.c:520:14: warning: unused variable ‘lenznext’ [-Wunused-variable]
     uint32_t lenznext = ctgs->seq[znext].len;
              ^
build_graph.c:519:14: warning: unused variable ‘lenz’ [-Wunused-variable]
     uint32_t lenz = ctgs->seq[z].len;
              ^
build_graph.c: In function ‘nns_straight’:
build_graph.c:630:13: warning: unused variable ‘len2’ [-Wunused-variable]
    uint32_t len2 = ctgs->seq[ind].len;
             ^
build_graph.c:618:12: warning: unused variable ‘len1’ [-Wunused-variable]
   uint32_t len1 = ctgs->seq[i].len;
            ^
build_graph.c: In function ‘nns_mst2’:
build_graph.c:736:10: warning: variable ‘ocnt’ set but not used [-Wunused-but-set-variable]
    float ocnt = 0;
          ^
build_graph.c: In function ‘main_bldg’:
build_graph.c:1080:8: warning: unused variable ‘msn’ [-Wunused-variable]
  float msn = .7, mdw = 0.95;
        ^
make: *** [build_graph.o] Error 1

**Comment by dfguan** [comment]
Thanks for trying pin_hic, I have updated the code. Could you please have a try? Any further questions, please feel free to contact me.  Best, Dengfeng

**Comment by Kmanjor** [comment]
Hi, 

I installed pin_hic successfully using the latest code. Thanks for your quick response. I will close this comment. 
Good luck.

Bests,
Kmanjor
